Repository NUMde/compass-numapp-frontend, pull requests merged in 2021-09, with the labels that each got.

#44 update github action
  .github/workflows/main_workflow.yaml
  .gitignore
  package.json
Labels: enhancement

#40 delete user specific config for xcode
  .gitignore
  ios/Compass.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/Compass.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Compass.xcodeproj/project.xcworkspace/xcuserdata/Golex.xcuserdatad/UserInterfaceState.xcuserstate
  ios/Compass.xcodeproj/project.xcworkspace/xcuserdata/jenny.xcuserdatad/UserInterfaceState.xcuserstate
  ios/Compass.xcodeproj/xcuserdata/Golex.xcuserdatad/xcschemes/xcschememanagement.plist
  ios/Compass.xcodeproj/xcuserdata/jenny.xcuserdatad/xcschemes/xcschememanagement.plist
  ios/Compass.xcodeproj/xcuserdata/skowalski.xcuserdatad/xcschemes/GCSStudie-Prod.xcscheme
  ios/Compass.xcodeproj/xcuserdata/skowalski.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: clean up

#52 Validation Check Fix
  src/components/modal/questionnaireModal.jsx
Labels: bug

#58 Fixing the send-questionnaire-response button on the CheckIn-Screen
  src/screens/checkIn/checkInScreen.jsx
Labels: bug

#60 updated the execution order of clareAll()
  src/screens/about/aboutContainer.jsx
Labels: bug

#56 replace 'btoa'
  App.jsx
  __tests__/Encryption.test.js
  package-lock.json
  package.json
  src/services/encryption/encryption.js
Labels: dependencies, clean up

#62 added error-messages to the login-screen (error-handling)
  src/config/textConfig.js
  src/screens/login/loginContainer.jsx
  src/screens/login/loginReducer.js
  src/screens/login/loginScreen.jsx
Labels: bug, enhancement

#64 Fix for the proper removal of a set subjectId
  src/screens/login/loginActions.js
  src/screens/login/loginReducer.js
Labels: bug

#68 fix comparison of codings
  src/components/modal/questionnaireModal.jsx
  src/services/questionnaireAnalyzer/questionnaireAnalyzer.js
Labels: bug
